name    'fewbytes/solr'
version '0.1.0'
source 'UNKNOWN'
author 'fewbytes'
license 'Apache License, Version 2.0'
summary 'Install and configure Solr cloud'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'puppetlabs/java', '>= 1.0.0'
dependency 'puppetlabs/stdlib', '>= 0.4.0'
dependency 'fewbytes/upstart', '>= 0.1.0'
dependency 'gini/archive', '> 0.1.0'
